In [2]:
import pandas as pd

In [3]:
csv_file_name = 'panda_mock_data.csv'

In [4]:
# Read the CSV file into a DataFrame
df = pd.read_csv(csv_file_name)

In [5]:
print(df)

      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Paris   70000
3    David   40    Berlin   80000
4      Eva   28     Tokyo   65000

In [6]:
df.head()

      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Paris   70000
3    David   40    Berlin   80000
4      Eva   28     Tokyo   65000

In [7]:
my_dataDictionary = {'d1': [1,2,3], 'd2': [11,12,13], 'd3': [111,121, 131], 'd4': [1111,1211, 1311]}
my_dataFrame = pd.DataFrame(my_dataDictionary)
print(my_dataFrame)

   d1  d2   d3    d4
0   1  11  111  1111
1   2  12  121  1211
2   3  13  131  1311

In [8]:
# ValueError: All arrays must be of the same length
my_dataDictionary = {'d1': [1,2,3], 'd2': [11,12,13], 'd3': [111,121, 131], 'd4': [1111,1211, 1311, 4444]}
my_dataFrame = pd.DataFrame(my_dataDictionary)
print(my_dataFrame)

ValueError: All arrays must be of the same length

In [25]:
my_dataDictionary = {'d1': [1, 2, 2], 'd2': [11,12,2.6], 'd3': [111,121, 'data 3'], 'd4': [1111,1211, 'data 4']}
my_dataFrame = pd.DataFrame(my_dataDictionary)
my_dataFrame.head()

   d1    d2      d3      d4
0   1  11.0     111    1111
1   2  12.0     121    1211
2   2   2.6  data 3  data 4

In [26]:
print(my_dataFrame.iloc[1,1]) # Location based indexing can only have integer
print(my_dataFrame.iloc[2,1])
print(my_dataFrame.loc[0,'d4']) # Location based on column name

12.0
2.6
1111

In [36]:
print(my_dataFrame.iloc[0:2,1])

0    11.0
1    12.0
Name: d2, dtype: float64

In [38]:
print(my_dataFrame.loc[0:2,'d4'])

0      1111
1      1211
2    data 4
Name: d4, dtype: object

In [39]:
print(my_dataFrame.loc[0:1,'d4'])

0    1111
1    1211
Name: d4, dtype: object

In [27]:
print(my_dataFrame.dtypes)
print(my_dataFrame['d1'].dtype) # datatype of a single column

d1      int64
d2    float64
d3     object
d4     object
dtype: object
int64

In [29]:
unique = my_dataFrame['d1'].unique()
print(unique)

[1 2]

In [30]:
my_dataFrame2 = my_dataFrame['d2'] > 10
print(my_dataFrame2)

0     True
1     True
2    False
Name: d2, dtype: bool

In [34]:
my_dataFrame2 = my_dataFrame[my_dataFrame['d2'] > 10]
print(my_dataFrame2)

   d1    d2   d3    d4
0   1  11.0  111  1111
1   2  12.0  121  1211